services:
  postgres:
    image: postgres:14
    container_name: mathildanesth_postgres
    environment:
      POSTGRES_USER: mathildanesth_user
      POSTGRES_PASSWORD: mathildanesth_password
      POSTGRES_DB: mathildanesth_db
    ports:
      - "5433:5432" # Changé de 5432 à 5433 pour éviter le conflit
    volumes:
      - postgres_data:/var/lib/postgresql/data # Stocke les données pour qu'elles persistent

  mongodb:
    image: mongo:latest
    container_name: mathildanesth_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mathildanesth

volumes:
  postgres_data: # Définit le volume pour stocker les données
  mongodb_data: # Volume pour MongoDB
