FROM node:18-alpine

WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port
EXPOSE 3000

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev"] 