export const publicHolidayService = {
  getPublicHolidaysInRange: jest.fn().mockResolvedValue([]),
  isPublicHoliday: jest.fn().mockResolvedValue(false),
  getPublicHolidaysForYear: jest.fn().mockResolvedValue([]),
  getHolidaysForYear: jest.fn().mockResolvedValue([]),
  getHolidaysForMonth: jest.fn().mockResolvedValue([]),
  checkAvailableBalance: jest.fn().mockReturnValue(true),
  calculateQuotaBalanceOnDate: jest.fn().mockReturnValue({
    consumed: 0,
    pending: 0,
    validated: 0,
    remaining: 30,
    total: 30,
    expires: null,
  }),
  getQuotaStatusOnDate: jest.fn().mockReturnValue('normal'),
  calculateHolidayDays: jest.fn().mockReturnValue(0),
  getNextPublicHoliday: jest.fn().mockReturnValue(null),
  getDaysUntilNextHoliday: jest.fn().mockReturnValue(null),
  convertZoneToUTC: jest.fn(date => date),
  convertUTCToZone: jest.fn(date => date),
  preloadData: jest.fn().mockResolvedValue(undefined),
};
